### ISSUE TITLE
Add RedPajama-INCITE 3B model (and perhaps more of the family)

### ISSUE THREAD

**Issue by suvash** [eugeneyan/open-llms#10]
I wasn't sure which of family of models released by TogetherCompute you'd like to add to the list, at least one of the RedPajama 3B/7B base models I guess. The 7B model is still training, but the 3B one is released. More info in their official release document.

I'll let you decide which one goes in the list. Thanks for making this repo.
- https://www.together.xyz/blog/redpajama-models-v1

Do feel free to close this ! 🙌🏽

**Comment by suvash** [comment]
I see you just added it.

**Comment by eugeneyan** [comment]
Yes, a recent [PR](https://github.com/eugeneyan/open-llms/pull/6) added the RedPajama models. Thanks for the intent!
