### ISSUE TITLE
Add release date column

### ISSUE THREAD

**Issue by moghadas76** [eugeneyan/open-llms#16]

**Comment by ericlecoutre** [comment]
+1 (with update date)

**Comment by eugeneyan** [comment]
Yes, that would be useful. Feel free to make a PR!

**Comment by adekunleoajayi** [comment]
@eugeneyan @moghadas76 I created a PR on this https://github.com/eugeneyan/open-llms/pull/23. Can you check it out?

**Comment by LudwigStumpp** [comment]
Thanks @adekunleoajayi for adding the dates. Very much appreciated!
Do you also want to add the release dates for the [LLMs for Code models](https://github.com/eugeneyan/open-llms#llms-for-code) down below?

**Comment by LudwigStumpp** [comment]
Due to lack of activity on this one, I will take over and will add the release dates for the code models now.

**Comment by LudwigStumpp** [comment]
Resolved with 3f31dba691a7d0d7697f58060eb250b3e0fc1670.

**Comment by adekunleoajayi** [comment]
> Due to lack of activity on this one, I will take over and will add the release dates for the code models now.

@LudwigStumpp sorry for the late reply on this. Please go for it. Thanks
