### ISSUE TITLE
performance benchmark

### ISSUE THREAD

**Issue by touhi99** [eugeneyan/open-llms#17]
Hi, 

are there possibility to add a performance benchmark of the open-sourced LLMs?

**Comment by LudwigStumpp** [comment]
Hi,

do you mean adding the performance results directly to the table?

For now, we have listed some external resources under the [Evals on open LLMs section](https://github.com/eugeneyan/open-llms#evals-on-open-llms), which cover the performances of the models on various baselines. Do you think this is enough?

**Comment by touhi99** [comment]
> Hi,
> 
> do you mean adding the performance results directly to the table?
> 
> For now, we have listed some external resources under the [Evals on open LLMs section](https://github.com/eugeneyan/open-llms#evals-on-open-llms), which cover the performances of the models on various baselines. Do you think this is enough?

Yes, that would give some rough idea which model to choose among many. I will have a look at the Evals, thanks.

Beside performance, personally, also GPU/tech requirement would also be interesting benchmark to estimate solution. If I propose, an LLM-based solution, what's the min. tech requirement would be for training/fine-tuning/inference. so far many models are coming in and out, but I haven't found any certain data. For example, X model need atleast Y gb gpu ram for inference.

**Comment by martinezpl** [comment]
For anyone interested in this topic: 

https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
