### ISSUE TITLE
OpenAlpaca and OpenChatKit

### ISSUE THREAD

**Issue by niutech** [eugeneyan/open-llms#26]
Please add [OpenAlpaca](https://github.com/yxuansu/OpenAlpaca) (based on OpenLlama) and [OpenChatKit](https://github.com/togethercomputer/OpenChatKit) (based on Pythia).

**Comment by omjaz909** [comment]
Running

**Comment by LudwigStumpp** [comment]
@omjaz909 great that you are working on this. What's the current status? Do you need any help?

**Comment by brianjking** [comment]
@niutech Do you know of any demos of OpenAlpaca or OpenLlama instances?

Secondly, isn't OpenChatKit what became the RedPajamas INCITE models which are already in the table? https://www.together.xyz/blog/redpajama-models-v1

**Comment by niutech** [comment]
@brianjking You can find both [OpenLlama demo](https://huggingface.co/openlm-research/open_llama_7b_400bt_preview) and [OpenAlpaca demo](https://huggingface.co/openllmplayground/openalpaca_7b_preview_3bt) on HuggingFace,

OpenChatKit is using two models: _GPT-NeoXT-Chat-Base-20B_ and _Pythia-Chat-Base-7B_.
