### ISSUE TITLE
Please add DLite

### ISSUE THREAD

**Issue by jacobrenn** [eugeneyan/open-llms#29]
Please add DLite to this list.

Name: DLite

Release Date: 2023/05

Blog post: https://medium.com/ai-squared/announcing-dlite-v2-lightweight-open-llms-that-can-run-anywhere-a852e5978c6e

Params (B): 0.124 - 1.5

Context Length: 1024

License: Apache 2.0

**Comment by eugeneyan** [comment]
Looks like you have all of the information available! Would you like to try [making a pull request](https://opensource.com/article/19/7/create-pull-request-github)?

**Comment by jacobrenn** [comment]
Absolutely!  Will do!

**Comment by LudwigStumpp** [comment]
Thanks for the contribution @jacobrenn! Great work from you and your team!
