### ISSUE TITLE
add ChatGLM?

### ISSUE THREAD

**Issue by Bdl-1989** [eugeneyan/open-llms#30]
https://github.com/THUDM/ChatGLM-6B

[Apache-2.0 license](https://github.com/THUDM/ChatGLM-6B/blob/main/LICENSE)

**Comment by LudwigStumpp** [comment]
Thanks for bringing this to our attention @Bdl-1989. Would like to create a PR which adds the ChatGLM model?

**Comment by Bdl-1989** [comment]
> Thanks for bringing this to our attention @Bdl-1989. Would like to create a PR which adds the ChatGLM model?

sure, a PR is coming
