### ISSUE TITLE
How come Vicuna isn't in the list?

### ISSUE THREAD

**Issue by tredondo** [eugeneyan/open-llms#35]
https://lmsys.org/blog/2023-03-30-vicuna/

> We introduce Vicuna-13B, an open-source chatbot trained by fine-tuning LLaMA on user-shared conversations collected from ShareGPT.

I'm not an expert (or I would've sent a PR), but Vicuna is quite well-known?

**Comment by kanslor** [comment]
Vicuna Based on Llama which is declared not for coomercial use.
