### ISSUE TITLE
Add Elo Ratings for each LLM

### ISSUE THREAD

**Issue by binga** [eugeneyan/open-llms#38]
Firstly, thank you so much for putting this list together! 

Is there a plan to add Elo ratings from https://lmsys.org/blog/2023-05-03-arena/ for each model in the table?

**Comment by LudwigStumpp** [comment]
Hi @binga, thanks for your intereset in this open-source project!

Currently, there are no plans to add model benchmark results into the table. Instead, we decided to provide external links to such overviews at the bottom of the [README](https://github.com/eugeneyan/open-llms#evals-on-open-llms).

Hope that helps!
