### ISSUE TITLE
Remove StableLM as model weights only include deltas to LLaMA model

### ISSUE THREAD

**Issue by LudwigStumpp** [eugeneyan/open-llms#4]
From the repository of StableLM (https://github.com/stability-AI/stableLM/):

> Due to the original non-commercial license of LlaMA, we can only release the weights of our model as deltas over the original model's weights. StableVicuna's delta weights are released under ([CC BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)).

Which means that the effective model cannot be used with the here specified `CC BY-SA-4.0` license, but effectively the `GPLv3` license of the LlaMA model applies for the merged one.

As this repository's intention is to provide an overview about open and commercially usable models, I would either propose to remove the StableLM model (unfortunately) or to indicate the above described issue with a note in the table.

What do you think?

**Comment by eugeneyan** [comment]
Good catch and thanks for the concise explanation. 

Would you like to make a PR to remove the StableLM model? Please also include this explanation, or link to this issue, in the PR. Thank you!

**Comment by LudwigStumpp** [comment]
Yes, will do!

**Comment by LudwigStumpp** [comment]
Okay, apparently there currently are two different models:

- `StableVicuna`: RLHF fine-tune of Vicuna-13B  which itself is a fine-tune of LLaMA-13B
- `StableLM-Alpha`: StableLM-Alpha models are trained on the new dataset that build on The Pile

My remark above applies for `StableVicuna`, but not for `StableLM-Alpha`. I would therefore propose to instead change the name of the table row entry from `StableLM` to `StableLM-Alpha` and adjust the corresponding link.

Will create the PR now.

**Comment by eugeneyan** [comment]
Updated merged.
