### ISSUE TITLE
OpenLLaMA's checkpoint page is currently unavailable

### ISSUE THREAD

**Issue by seekincs** [eugeneyan/open-llms#41]
The link [OpenLLaMA-7b-preview-300bt](https://huggingface.co/openlm-research/open_llama_7b_preview_300bt) is now a 404 page.

**Comment by eugeneyan** [comment]
Thanks for raising this to our attention! [Fixed](https://github.com/eugeneyan/open-llms/commit/6908c9bb7d1c7870cddbfa1cd44538f7b7b29c93)
