### ISSUE TITLE
The arxiv link for GPT-Neox-20B is incorrect

### ISSUE THREAD

**Issue by 13-05** [eugeneyan/open-llms#47]
this is the current link:

![image](https://github.com/eugeneyan/open-llms/assets/64506392/afd8300e-c5cb-41df-9a98-23b1e5dbe57d)

it should be https://arxiv.org/abs/2204.06745, which is:

![image](https://github.com/eugeneyan/open-llms/assets/64506392/b6ed921e-1c5f-4237-a393-216581af569a)

**Comment by eugeneyan** [comment]
Thanks for catching this! Would you like to open a pull request to update the readme so we can credit you for it? =)

**Comment by 13-05** [comment]
> Thanks for catching this! Would you like to open a pull request to update the readme so we can credit you for it? =)

It would likely be easier (and faster!) for you to just commit to the main repository directly and due to the fact that this is such a simple error, I don't need "credit" for finding it haha.

**Comment by eugeneyan** [comment]
Fixed here: https://github.com/eugeneyan/open-llms/commit/23df358fcc66598e967a5d141526d65807d8a419
