### ISSUE TITLE
baichuan-7B is not under Apache 2.0 license 

### ISSUE THREAD

**Issue by jeff31415** [eugeneyan/open-llms#49]
baichuan-7B is under a coustom license,refer to https://huggingface.co/baichuan-inc/baichuan-7B/blob/main/baichuan-7B%20%E6%A8%A1%E5%9E%8B%E8%AE%B8%E5%8F%AF%E5%8D%8F%E8%AE%AE.pdf
This should be distinguished from most opensource license.

**Comment by eugeneyan** [comment]
I think you may be right, especially section 2.2 in the license which states: 

> 2.如果您计划将baichuan-7B模型及模型衍生品用作商业用途，应当按照本协议附则提供的联络方式，事先向许可方登记并获得许可方的书面授权。

Translation: If you plan to use the baichuan-7B model and model derivatives for commercial purposes, you should register with the licensor in advance and obtain written authorization from the licensor according to the contact information provided in the appendix of this agreement.

I think this is sufficiently onerous for it to not be considered an open LLM that can be used for commercial purposes. (Also, the Apache 2.0 license on their [repo](https://github.com/baichuan-inc/baichuan-7B) is misleading.)

I'm inclined to remove it as long as the custom license is attached to the [weights on huggingface](baichuan-inc/baichuan-7B). What do you think @LudwigStumpp @Muhtasham?

**Comment by Muhtasham** [comment]
Agree @eugeneyan sorry for oversight

**Comment by eugeneyan** [comment]
Fixed here: https://github.com/eugeneyan/open-llms/commit/fe99aceb927857cd73c7cab6ca37569cf0095423
