### ISSUE TITLE
Update few models

### ISSUE THREAD

**Issue by jeff31415** [eugeneyan/open-llms#50]
1:Redpajama incite now have fully trained 7B weight released.
2:StarCoder plus:https://huggingface.co/bigcode/starcoderplus
It was trained Futher on 600B additional data,Futher improving its performance.Also,I notice that it can also used as a chat bot now(thank to general English data from refined web),performing similar to llama 13b based models,and with 8192 ctx.
3:Tiger bot release it's giant 180B model.https://huggingface.co/TigerResearch/tigerbot-180b-research
Seems under Apache 2.0 license(no any other license or restriction mentioned on their repo,and every repo is shown Apache 2.0 license,but did not mention explicitly about their model license.) I hope it is truelly under Apache 2.0 license.
7B base and sft model available also.

**Comment by Muhtasham** [comment]
Do you want to create PR so you get credited?

**Comment by jeff31415** [comment]
> Do you want to create PR so you get credited?

great
