### ISSUE TITLE
OpenLLaMa

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [eugeneyan/open-llms#62]
Isn't [OpenLLaMa](https://huggingface.co/openlm-research/open_llama_13b) supposed to be in this list ?

**Comment by LudwigStumpp** [comment]
Hi @BinaryQuantumSoul,

thanks for your interest in this collective open-source work.
OpenLLaMa is already part of the table. However I just saw that the referenced checkpoints are outdated. Do you want to update them by the reference you just provided?

If so, feel free to quickly create a PR and mention this issue as a reference. I will take care of merging it.

Best,
Ludwig

**Comment by BinaryQuantumSoul** [comment]
Hello,
Sorry, I'm really not that much good at reading at table 🤣. I don't have time right now for PR. But anyway this table is mainly useful for model names since they are constantly updating.

Have a good day/night

**Comment by LudwigStumpp** [comment]
Sure, no worries,
then I will take this over and correct the link. Thanks for bringing this to our attention.
