### ISSUE TITLE
Shouldnt there be some consideration of Llama 2 now? 

### ISSUE THREAD

**Issue by andymiller-og** [eugeneyan/open-llms#63]
Now that Llama2 has been [released](https://ai.meta.com/llama/), looks like an update is in order.

**Comment by Muhtasham** [comment]
Its not really open source, please see attached

https://opensourceconnections.com/blog/2023/07/19/is-llama-2-open-source-no-and-perhaps-we-need-a-new-definition-of-open/

**Comment by Artur-Galstyan** [comment]
Well, the description of this repo states:

> These LLMs (Large Language Models) are all licensed for commercial use [...]

But realistically: do you have 700M users? Likely, no; so for most people, who want to **use** LLaMA 2, this is of no concern. Also, people who are looking for LLMs to actually use e.g. for support chatbots will not care if you cannot use it to train another LLM (why would they, given that it's super expensive and you already have LLaMA). 

As a user of this repository, I'd actually be a bit disappointed if LLaMA didn't appear in here. Perhaps you might add a footnote, like "only for <700M users; not for training other LLMs".

**Comment by Muhtasham** [comment]
@eugeneyan @LudwigStumpp what's your take on this?

**Comment by eugeneyan** [comment]
I agree that the license is not open-source, especially the clauses below:

> 2. Additional Commercial Terms. If, on the Llama 2 version release date, the monthly active users of the products or services made available by or for Licensee, or Licensee’s affiliates, is greater than 700 million monthly active users in the preceding calendar month, you must request a license from Meta, which Meta may grant to you in its sole discretion, and you are not authorized to exercise any of the rights under this Agreement unless or until Meta otherwise expressly grants you such rights.

> v. You will not use the Llama Materials or any output or results of the Llama Materials to improve any other large language model (excluding Llama 2 or derivative works thereof).

Nonetheless, I believe a majority of users aren't part of that FAANG clause, and are likely focused on using Llama2 directly (instead of using it to generate demonstration data). 

Thus, I would be inclined to include Llama with a link to Llama2's license, and to call out that **"not for >700M MAU orgs; not for improving other LLMs"**. 

Would either @andymiller-og or @Artur-Galstyan like to make a PR?

**Comment by Artur-Galstyan** [comment]
I've created a PR
