### ISSUE TITLE
Open Hermes

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [eugeneyan/open-llms#74]
Hello,

Thanks for this beautiful resource.

Please add OpenHermes too.

https://huggingface.co/teknium/OpenHermes-7B
https://huggingface.co/teknium/OpenHermes-13B

Best,
Orkut

**Comment by eugeneyan** [comment]
Sure, would you like to make a pull request please?

**Comment by orkutmuratyilmaz** [comment]
Sorry @eugeneyan, I've just seen your reply. I'm glad to contribute:)

**Comment by eugeneyan** [comment]
Resolved with https://github.com/eugeneyan/open-llms/pull/76
