### ISSUE TITLE
Please add summaries

### ISSUE THREAD

**Issue by Rudxain** [eugeneyan/open-llms#79]
I'm an advocate for minimalism and self-documenting code. I understand that the links are "just enough info" that there shouldn't be need for summaries.

However, I would appreciate if each model had a 1-line summary (or, if possible, multiple tiny lines explaining "the what and the why").

Not everyone has time to click every link and read the pages pointed by them.

I just came here and I see all of the models as "the same thing". I genuinely have no idea which ones are appropriate for my use-cases.

I'm willing to visit all URLs, to open a PR for this, but I don't have time this month.

BTW, thanks to all contributors for their time! And I'm sorry for my ignorance (if there's already a summary that I missed)

**Comment by eugeneyan** [comment]
I think you have a good point! Sure, we would appreciate the PR whenever you have the time. Thank you!

**Comment by Rudxain** [comment]
Why was this closed as "completed"?

BTW, I've changed my mind: Not every LLM needs a summary. The only ones that do, are the ones with missing info in the main table. So I guess this issue should be closed, because eventually all missing info will be filled in
